version: "2.1"
services:
  jellyfin:
    image: jellyfin/jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      # This can grown large, 50gb+ for a large collection
      - ${APP_DATA_DIR}/jellyfin-config:/config
      - ${APP_DATA_DIR}/jellyfin-cache:/cache
      - ${MEDIA_DIR}/tvshows:/media/tvshows
      - ${MEDIA_DIR}/movies:/media/movies
    ports:
      - 8096:8096
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - ${APP_DATA_DIR}/sonarr-config:/config
      - ${MEDIA_DIR}/tvshows:/tv
      - ${DOWNLOADS_DIR}/transmission-downloads/complete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - ${APP_DATA_DIR}/radarr-config:/config
      - ${MEDIA_DIR}/movies:/movies
      - ${DOWNLOADS_DIR}/transmission-downloads/complete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - ${APP_DATA_DIR}/nzbget-config:/config
      - ${DOWNLOADS_DIR}/nzbget-downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - ${APP_DATA_DIR}/transmission-config:/config
      - ${DOWNLOADS_DIR}/transmission-downloads:/downloads
      - ${APP_DATA_DIR}/transmission-watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - ${APP_DATA_DIR}/jackett-config:/config
    ports:
      - 9117:9117
    restart: unless-stopped

